/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 *
 * openGauss is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

package org.postgresql.core;

import org.postgresql.jdbc.ORResultSet;
import org.postgresql.jdbc.ORStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * query cache
 *
 * @author zhangting
 * @since  2025-06-29
 */
public class ORCachedQuery {
    private ORResultSet rs;
    private ORStatement statement;
    private ORBaseConnection conn;
    private String sql;
    private String parsedSql;
    private int paramCount;
    private boolean isPrepare;
    private boolean isAutoGeneratedKeys = false;
    private ORResultSet generatedKeys;
    private List<byte[]> lobDatas;
    private int lobDataLen;
    private int lobOffset;
    private boolean hasLob;
    private byte[] lobValue;

    /**
     * cached query constructor
     *
     * @param conn connection
     * @param statement statement
     * @param sql sql
     * @param isPrepare is prepare
     */
    public ORCachedQuery(ORBaseConnection conn, ORStatement statement, String sql, boolean isPrepare) {
        this.conn = conn;
        this.statement = statement;
        this.sql = sql;
        this.paramCount = parseSql(sql);
        this.isPrepare = isPrepare;
    }

    /**
     * cached query constructor
     *
     * @param conn connection
     * @param statement statement
     * @param isPrepare is prepare
     */
    public ORCachedQuery(ORBaseConnection conn, ORStatement statement, boolean isPrepare) {
        this.conn = conn;
        this.statement = statement;
        this.isPrepare = isPrepare;
        this.lobDatas = new ArrayList<>();
        this.hasLob = true;
    }

    /**
     * get connection
     *
     * @return connection
     */
    public ORBaseConnection getConn() {
        return conn;
    }

    /**
     * if is prepare
     *
     * @return is prepare
     */
    public boolean isPrepare() {
        return isPrepare;
    }

    /**
     * add lob data
     *
     * @param lobData part lob data
     */
    public void setLobData(byte[] lobData) {
        this.lobDatas.add(lobData);
    }

    /**
     * get lob data
     *
     * @return lob data
     * @throws SQLException if a database access error occurs
     */
    public byte[] getLobData() throws SQLException {
        byte[] data = new byte[lobDataLen];
        int position = 0;
        for (byte[] lobData : lobDatas) {
            int leftLen = lobDataLen - position;
            if (leftLen < lobData.length) {
                throw new SQLException("get lob data failed.");
            }
            System.arraycopy(lobData, 0, data, position, lobData.length);
            position += lobData.length;
        }
        return data;
    }

    /**
     * set lob data length
     *
     * @param dataLen lob data length
     */
    public void setLobDataLen(int dataLen) {
        this.lobDataLen = dataLen;
    }

    /**
     * get lob data length
     *
     * @return lob data length
     */
    public int getLobDataLen() {
        return lobDataLen;
    }

    /**
     * set lob offset
     *
     * @param lobSize lob data size
     */
    public void setLobOffset(int lobSize) {
        this.lobOffset += lobSize;
    }

    /**
     * get lob offset
     *
     * @return lob offset
     */
    public int getLobOffset() {
        return lobOffset;
    }

    /**
     * set hasLob
     *
     * @param hasLob has lob data
     */
    public void setHasLob(boolean hasLob) {
        this.hasLob = hasLob;
    }

    /**
     * get hasLob
     *
     * @return hasLob
     */
    public boolean getHasLob() {
        return hasLob;
    }

    /**
     * set lob value
     *
     * @param lobValue lob value
     */
    public void setLobValue(byte[] lobValue) {
        this.lobValue = lobValue;
    }

    /**
     * get lob value
     *
     * @return lob value
     */
    public byte[] getLobValue() {
        return lobValue;
    }

    /**
     * Whether to return generated keys
     *
     * @return isAutoGeneratedKeys
     */
    public boolean isAutoGeneratedKeys() {
        return isAutoGeneratedKeys;
    }

    /**
     * set auto generated keys
     *
     * @param isAutoGeneratedKeys Whether to return generated keys
     */
    public void setAutoGeneratedKeys(boolean isAutoGeneratedKeys) {
        this.isAutoGeneratedKeys = isAutoGeneratedKeys;
    }

    /**
     * get param count
     *
     * @return param count
     */
    public int getParamCount() {
        return paramCount;
    }

    private int parseSql(String sql) {
        if (sql == null) {
            return 0;
        }

        String formatSql = getFormatSql(sql.trim());
        char[] cs = formatSql.toCharArray();
        StringBuilder sqlSb = new StringBuilder(cs.length + 10);
        int index = 0;
        int params = 0;
        while (index < cs.length) {
            if (cs[index] == '\'') {
                index = parseQuotes(sqlSb, cs, index, '\'');
            } else if (cs[index] == '"') {
                index = parseQuotes(sqlSb, cs, index, '"');
            } else if (cs[index] == '-') {
                index = parseLine(sqlSb, cs, index);
            } else if (cs[index] == '?') {
                params++;
                index = parseParam(sqlSb, index, params);
            } else if (cs[index] == '/') {
                index = parseLines(sqlSb, cs, index);
            } else {
                sqlSb.append(cs[index]);
                index++;
            }
        }

        this.parsedSql = sqlSb.toString();
        return params;
    }

    private String getFormatSql(String sql) {
        if (sql.startsWith("{") && sql.endsWith("}")) {
            return sql.substring(1, sql.length() - 1);
        }
        return sql;
    }

    private int parseQuotes(StringBuilder sqlSb, char[] cs, int index, char target) {
        int p = index;
        sqlSb.append(cs[p++]);
        while (p < cs.length) {
            sqlSb.append(cs[p]);
            if (cs[p] == target) {
                p++;
                return p;
            }
            p++;
        }
        return p;
    }

    private int parseLine(StringBuilder sqlSb, char[] cs, int index) {
        int p = index;
        sqlSb.append(cs[p++]);
        if (p >= cs.length || cs[p] != '-') {
            return p;
        }
        sqlSb.append(cs[p++]);
        while (p < cs.length) {
            if (cs[p] == '\r' || cs[p] == '\n') {
                return p;
            }
            sqlSb.append(cs[p++]);
        }
        return p;
    }

    private int parseParam(StringBuilder sqlSb, int index, int paramCount) {
        int p = index;
        sqlSb.append(":p").append(paramCount);
        return ++p;
    }

    private int parseLines(StringBuilder sqlSb, char[] cs, int index) {
        int p = index;
        sqlSb.append(cs[p++]);
        if (p < cs.length && cs[p] == '*') {
            sqlSb.append(cs[p++]);
            while (p < cs.length) {
                sqlSb.append(cs[p]);
                char c = cs[p];
                p++;
                if (c == '*' && cs[p] == '/' && p < cs.length) {
                    sqlSb.append(cs[p++]);
                    break;
                }
            }
        }
        return p;
    }

    /**
     * get statement
     *
     * @return statement
     */
    public ORStatement getStatement() {
        return statement;
    }

    /**
     * get parsed sql
     *
     * @return parsed sql
     */
    public String getParsedSql() {
        return parsedSql;
    }

    /**
     * get resultSet
     *
     * @return resultSet
     */
    public ResultSet getRs() {
        return rs;
    }

    /**
     * set data rows to the resultSet
     *
     * @param fields column fields
     * @param valueLens value length
     * @param rows data rows
     * @param hasRemain is there still data available
     * @throws SQLException if a database access error occurs
     */
    public void handleResultRows(ORField[] fields, List<int[]> valueLens, List<byte[][]> rows,
                                 boolean hasRemain) throws SQLException {
        this.rs = new ORResultSet(this.statement, sql, fields, valueLens, rows, hasRemain,
                statement.getResultSetType(), statement.getResultSetConcurrency());
    }

    /**
     * set generated keys to the resultSet
     *
     * @param fields column fields
     * @param valueLens value length
     * @param rows data rows
     * @param hasRemain is there still data available
     * @throws SQLException if a database access error occurs
     */
    public void handleGeneratedKeys(ORField[] fields, List<int[]> valueLens, List<byte[][]> rows,
                                    boolean hasRemain) throws SQLException {
        this.generatedKeys = new ORResultSet(this.statement, sql, fields, valueLens, rows, hasRemain,
                statement.getResultSetType(), statement.getResultSetConcurrency());
    }

    /**
     * set resultSet
     *
     * @param rs resultSet
     */
    public void setRs(ORResultSet rs) {
        this.rs = rs;
    }

    /**
     * update fetch data to the resultSet
     *
     * @param total rows total
     * @param valueLens value length
     * @param rows data rows
     * @param hasRemain is there still data available
     */
    public void setNewData(int total, List<int[]> valueLens, List<byte[][]> rows, boolean hasRemain) {
        rs.setFetchInfo(total, valueLens, rows, hasRemain);
    }

    /**
     * get generated keys
     *
     * @return generated keys
     */
    public ORResultSet getGeneratedKeys() {
        return generatedKeys;
    }

    /**
     * set sql query
     *
     * @param sql sql query
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * get sql
     *
     * @return sql
     */
    public String getSql() {
        return sql;
    }
}